### ISSUE TITLE
Free rerolls of soak rolls still spend a bennie.

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#105]

**Comment by Razortide** [comment]
You can do Soak rolls?

**Comment by javierriveracastro** [comment]
Yes. With some bugs.

**Comment by Razortide** [comment]
Uh, I would like to see that? I haven't seen something in the documentation (looks a bit outdated) :-)

**Comment by SalieriC** [comment]
Here you go @Razortide:
![image](https://user-images.githubusercontent.com/1230041/107746917-ea260380-6d16-11eb-9977-ad4a7d17a34f.png)
After rolling:
![image](https://user-images.githubusercontent.com/1230041/107746949-f4e09880-6d16-11eb-8352-a84cc14ee914.png)
Surreptitious advertising for SWADE Spices & Flavours not intentional. XD

**Comment by Razortide** [comment]
Thank you @SalieriC, I was wondering how to get that Soak card :-)

**Comment by javierriveracastro** [comment]
That's a valid bug. Documentation is wayyyyyyyy obsolete.

**Comment by javierriveracastro** [comment]
Solved.
