### ISSUE TITLE
Show an alert when power points will go below 0 with the current casting

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#114]
I just found that the power points deduction below 0 will not raise an error:
![image](https://user-images.githubusercontent.com/35796457/107864892-72182480-6e61-11eb-940f-aeb022a55f29.png)

I used the "Manual PP management" option to reach that solution.

If there could be a warning message if the power points would go below 0 with the current casting, this would be helpful.

**Comment by javierriveracastro** [comment]
That's clearly a bug, should work like shots.

**Comment by javierriveracastro** [comment]
I have added a message similar to manual shots. So kinda solved.

The problem is manual and automatic management work different. Manual show a notification and automatic a card. They should probably do it the same way.

Right now I'm for a notification as chat is full enough. But the chat card gives more info, like who is expending pps and it keeps an history. I'd leave the bug open until a decision is made.
