### ISSUE TITLE
When Recharging PP displayed updated value is not checking max power points

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#116]
Hello Javier,

I just found when I am using the recharging option in the Manual PP management action, it will not show the correct updated value:

I added 15 PP to a character that only has a max of 10. Here is the result:

![image](https://user-images.githubusercontent.com/35796457/108054270-b7e61000-704e-11eb-800e-d22f09b185b1.png)

**Comment by SalieriC** [comment]
Since the code originally comes from me, I feel the need to comment here. This is - by all means and purposes - the intended behaviour. Power Points can only vera rarely be over their maximum. This can not happen when using a Benny or by natural regeneration (which the macro is supposed to simulate), this is why I did it like that.
The chat message could be fixed though...

**Comment by Razortide** [comment]
Hey SalieriC, sorry for being unclear. That was my point. The chat message should show 10 instead of 16.
Thanks for pointing it out.

**Comment by Razortide** [comment]
Same for Benny recharge.

**Comment by SalieriC** [comment]
Should be easy to fix though, you want me to take a look at it @javierriveracastro?

**Comment by javierriveracastro** [comment]
Sure

**Comment by SalieriC** [comment]
I wanted to do it a bit differently but due to Javiers efficient way to write code I couldn't do it quickly. It should fix the problem though. When I have more time I might come back to it and create a notification recharging would've overflowed the maximum to inform the user about it to prevent confusion. Let me know whether or not that is necessary please.

**Comment by javierriveracastro** [comment]
Closed.
