### ISSUE TITLE
Basic shooting roll uses max RoF for a weapon.

### ISSUE THREAD

**Issue by QckSilverDragon** [javierriveracastro/betteroll-swade#137]
This can be a bit confusing because any weapon with RoF 2 or more has extra action for any attach made over 1 RoF.
![image](https://user-images.githubusercontent.com/4044050/110061370-1be62500-7d2d-11eb-893b-b94ff8315be1.png)
All the weapons included with the core rules has this setup. 
Any time you use the basic system to do a shooting roll it only makes one trait die roll. Can you make it so Better rolls does the same as the system?

**Comment by javierriveracastro** [comment]
Well, I like it the way that it is. While is true that all weapons in core rules have actions created for then, other weapons don't, and creating them is a chore.

I also enjoy creating different weapons for each "action" instead of using "system" actions, so that I can make a one-click roll. Like having gun (ROF:1) and gun (ROF:2) in the sheet. You proposal will make this approach unworkable.

I'll leave this issue open, so you or other people can comment, but unless I'm missing something this will be closed as non-fix.

**Comment by SalieriC** [comment]
Can't you just overwrite this using the Number of Trait Dice? Also using the chat card only and then choosing the desired action could fix that without taking away the functionality of using the entire RoF by default. I don't think many people enjoy having copies of the same weapon (including myself) but prefer using the actions.

**Comment by javierriveracastro** [comment]
The actual way of working let's you choose your poison. Either use actions or create copies.

The propossed change (using always rof 1) will make the making copies approach unworkable.

We are just talking about default rolls, cards, number of trait dice, etc... is not affected by this issue AFAIK.

**Comment by SalieriC** [comment]
Sorry, the first two sentences were directed at @QckSilverDragon, not you @javierriveracastro. Should've made that more clear.

**Comment by QckSilverDragon** [comment]
Could you make a setting option to toggle it?
I dont like having to add a bunch of copies of weapons to my item list. How do you manage shot count for each "copy"? Do you manually adjust the ammo count for all "RoF" copies of a weapon when you shoot?

I guess if i wanted to keep using Better rolls i could go through and edit all my weapons to add a RoF 1. Downside is it could easily get confusing for people and they may accidentally forget to enable the RoF 1 and will expend too many shots. Now they have to manually edit their ammo back.

You are the developer so it is ultimately up to you, i just think deviating from core functionality can add confusion. If you can make a setting for it i think that would give everyone the best usability.

**Comment by javierriveracastro** [comment]
I don't count shots. :).
But I come from playing on a real table, where counting shots was anathema to Fast, Fun, Furious. If I had started on a VTT maybe I would.
Sure, an option will work for everybody.

**Comment by QckSilverDragon** [comment]
We use shots, even in IRL, because our group has a tenacity to forget to carry enough.
Im also currently running Deadlands and players tend to leave the "extra" ammo on their horses while in a fight. Makes for interesting combat when they run out and have to deal with it. Has resulted in some entertaining social conflicts.

**Comment by javierriveracastro** [comment]
That's the same reason that we didn't. We don't want to care about carrying enough ammunition or not. We assume that our characters, having their lives dependent on it, would take much more care than us.

When it was important for the story we use the "loose a ammunition level on 1" quick trick.

**Comment by QckSilverDragon** [comment]
I see the benefit. Similar to how encumbrance isn't always used.

**Comment by SalieriC** [comment]
@QckSilverDragon , why don't you just use the 1 Trait Die modifier in the chat or a chat card instead of direct roll? Is it that cumbersome for you that it needs a setting option?

**Comment by QckSilverDragon** [comment]
@SalieriC I'm trying to use the better rolls 2 card so it will do all its magical automation. If i manually make the roll like you suggest then why bother using better roll 2 in the first place? Its not cumbersome to make the roll, im wanting to use the automation this module provides. 

Transitioning from the core system which rolls RoF 1 when using the weapon card, better rolls 2 does full RoF roll be default. This is just a little confusing. Especially when all the default weapons brought in by the core rules are built with RoF >1 actions added to them. They are built with the expectation of core system functionality. 
I am just asking if we can get similar functionality with better rolls 2. If adding a setting (even if its off by default) this would help with people that dont want 3 different gattling pistols in their inventory that they have to manage shot counts on just so they get full RoF options.

**Comment by SalieriC** [comment]
@QckSilverDragon I would argue that the default using full RoF indeed is automation but anyway. Did you get what I'm after here? you can just set the Trait die modifier to permanently be 1:
![image](https://user-images.githubusercontent.com/1230041/110192493-c2661f00-7e2e-11eb-85dc-b81662fab796.png)
(Double click it to become red.) Then you don't need to worry about it anymore. It then will always use RoF1 instead of the full RoF. That's hardly a constraint of the automation, is it?

**Comment by QckSilverDragon** [comment]
@SalieriC 
I didnt know setting it to red made it permanent.
Do you then have to turn it off if you actually use an RoF action of >1?

My main request was to ask if the process could resemble the core system functionality so that it produces less confusion for people and pre-made weapons. If you feel you dont want to or its in the wrong direction of the module that is fine. 
People will be able to find a work around to how the module functions. Either adding a RoF 1 action to their weapons and training the players or using the forced modifier for that one attack.
Im sure Im not the only one that tracks ammo making multiple copies of the same weapon not practical.

**Comment by SalieriC** [comment]
@QckSilverDragon Yes, using anything greater than RoF 1 would then require to deactivate the modifier. But that's only necessary when you really want to do that for all other Trait rolls it would be fine to leave it activated.
I  don't know I really like it the way it is because when I have a weapon with RoF >1 I usually want to autofire. But maybe that's just me.

**Comment by javierriveracastro** [comment]
I will close this as Won't Fix until some one add some other rationale to it.
