### ISSUE TITLE
Add support for Test rolls

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#155]
When I roll for a Skill, I wish I could tell I'm attempting a Test against my targeted opponent.

I don't know what would be the best way to present it.
We need to roll with options to reroll, until we confirm the result we want to keep. Then it would pop an Attribute roll card to the opponent to roll using my confirmed roll as his TN.
Ideally, success or failure or failure with a raise on the attacker's part, would give me the opportunity to set Distracted or Vulnerable and Shaken.

![image](https://user-images.githubusercontent.com/38113746/111471483-3b1b8400-8729-11eb-8b66-89ad38dd21cc.png)

**Comment by SalieriC** [comment]
Hmm, global actions, maybe?

**Comment by javierriveracastro** [comment]
Maybe. Or maybe a dedicated card for contested actions. Anyway, this will have to wait in the queue as it is going to be time consuming.

**Comment by CyrilRonseaux** [comment]
The more I think about it, the harder it is to implement it **right**.

The first minimal step (which might be all we actually need to do, further automatisation might be optional), would be:
to have a way to display the final total instead of a fail/success/raise (which you already in fact have if you unfold the "result" panel). Maybe a button "opposed" near the "global actions" section, which turns the "result" section into displaying : crit fail (double 1), fail (below 4) or final roll (with no mention of success or raise).  (A global action sets modifiers, which isn't the case here, but the top of the card is still a good place to have the "opposed" toggle)

Then the owner of the defending actor could roll his attribute by himself (or roll Notice for Stealth vs Notice, or athletics for Grapples...) and input the difficulty taken from the initial roll.

Automating applying the test result might be risky. by RAW, the initiator has to pick Vulnerable or Distracted, but on a raise "or there may be other subjective effects as the GM allows, such as a tripped foe being knocked prone.". You also have Creative Combat. If you add Dirty Fighter Edges from various add-ons or setting, it's too many valid options.

**Comment by SalieriC** [comment]
Since this is a rather old ticket, maybe it is time to reflect whether this really needs to be done. I'm unsure the amount of work that needs to be done for this is worth the effort. Sure it would add to the automation, but how difficult is it to compare two numbers? Or to manually enter the target number? There are also very many things to consider. Tests can result in Distracted or Vulnerable or +Shaken on a Raise or - to further complicate things - on a roll on a table. So another Setting rule would be needed as well as new buttons to assign either Vulnerable or Distracted.
If this is really done however, Support tests would need to be done as well for consistency which adds even more work. It's up to @javierriveracastro to decide but I'm not sure it really is needed.

**Comment by CyrilRonseaux** [comment]
Hi.

I would say, the main goal I envisioned here, was to automatically use the roll of the attacker to set the difficulty to the defender's roll. As you said, the result is displayed and it's easy to compare rolls.

As for the result of a Test, to further complicate things, there are Edges in many settings that allow to place Vulnerable/Distracted+Shaken on success and V+D+S on raise, or do other effects. Also, by RAW, the GM may choose to apply another effect than Shaken on a raise (see the example that sets Prone).

So I agree, this issue is much more complex than it looks (from a business/behaviour point of view) and does not add that much to the automation.

I agree to cancel it.
