### ISSUE TITLE
Creating "Selected Token" based macros

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#165]
Hello Javier,

when I drag and drop a Skill to the Macro Bar, the code looks something like this:

game.brsw.create_skill_card_from_id('PM5sNFICSzrgxvBy', 'Ydh4yF1ZWGKAnHu3', 'O3v4vDE2LrCwMq8n').then(
            message => {game.brsw.roll_skill(message, "", false)})

My question is: Is there a way to, instead of hard coding the actor, use a "selected token" part? 

So that as a GM I can setup the most common skills (and attributes) in my Makro bar and it will take the corresponding value?

If I have the Skill Intimidation in my Makro bar and select Token A it will take the Intimidation value of actor A and if I switch to Token B it will use the Intimidation value of Actor B.

**Comment by SalieriC** [comment]
I'm kinda glad it is linked to the specific actor. But maybe having this as an option would be beneficial for some GMs. Custom Hotbar + Token Hotbar however works great together with BR2 because you can then set up the custom hotbar with Macros specific for the selected Actor/Token. The macros get changed when another token is selected. Maybe that helps you in the meantime @Razortide?

**Comment by javierriveracastro** [comment]
You can use:

`game.brsw.create_skill_card(token or actor, skill_id)`

Not tested and just from memory (so something is wrong for sure), something like that:

`game.brsw.create_skill_card(canvas.token.controlled[0], canvas.token.controlled[0].actor.items.filter((item => {return item.name === 'skill_name'}).id);
`

You should probably test for a selected token and the type of the item, but you get the idea.
