### ISSUE TITLE
Getting error while trying to setup Soak roll macro

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#199]
Hey Javier,

I am encountering an error while trying to create a Soak roll macro that uses BRSW API

(First: Call is game.brsw.create_atribute_card(token, name) instead of create_attribute_card)

Secondly, here is my call:

```
	let br_card = game.brsw.create_atribute_card(token, 'spirit');
	const r = await game.brsw.roll_attribute(br_card, '', false);
```

Here is the error message:
![image](https://user-images.githubusercontent.com/35796457/118720053-6f92e580-b829-11eb-8733-a8cdf5bfe498.png)

It points to line 205 in the cards_common.js which is:
```
export function get_actor_from_message(message){
    return get_actor_from_ids(
        **message.getFlag('betterrolls-swade2', 'token'),**
        message.getFlag('betterrolls-swade2', 'actor')
    );
 }
```

I have found that objects of type ChatMessage (the message) do not have a function getFlag, Actors and Tokens however do have that. Am I missing something here?

https://foundryvtt.com/api/ChatMessage.html
https://foundryvtt.com/api/Token.html#getFlag

Marc

**Comment by javierriveracastro** [comment]
All entities have getFlag (https://foundryvtt.com/api/Entity.html#getFlag).

And you can't await there. You can only await inside async functions. To be able to await you will need to surround all the macro inside one.

But you are right with the await thing, the problem is that the card is not yet created when you call the roll.

This works

```
(async () => {
let br_card = await game.brsw.create_atribute_card(token, 'spirit');
const r = game.brsw.roll_attribute(br_card, '', false);
})();
```
This also works using promise chaining instead of awaits.

```
game.brsw.create_atribute_card(token, 'spirit').then(
br_card => {
    game.brsw.roll_attribute(br_card,'',false);
});
```
