### ISSUE TITLE
Global Switches

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#315]
Hi.

Is it possible to create a global switch above the chat?
![image](https://user-images.githubusercontent.com/4999783/130625256-965982f5-7dca-4840-8e93-6c7bff93f3b2.png)

A global switch is a button which only the GM can click. But, after that, all rolls will check if the button is on. It'll work like any other global action.
- Unstable Plataform
- Ilumination

**Comment by brunocalado** [comment]
Fantasy Grounds
![image](https://user-images.githubusercontent.com/4999783/130628175-a166b502-016c-4455-b742-a3c8c92f31f2.png)

**Comment by SalieriC** [comment]
I like the idea, especially for illumination. But I'd prefer another location, otherwise the chat will become rather crowded.

**Comment by Razortide** [comment]
Would a macro be a feasible solution that opens a page where you can turn actions on  and off?

**Comment by javierriveracastro** [comment]
We should probably merge this and #314 and redesign the betterroll modifier window.

It should probably include some way to let the master set the modifiers for the player's rolls.

It will not get done quickly, but a design goal will probably help.

**Comment by SalieriC** [comment]
Instead of taking up a macro slot for that, we could register it to the left bar controls. Will only work with a scene but who plays without any form of scene (and if it is only a static image) anyway? Either under token controls or a dedicated new option for multiple things although I'd prefer it under token controls as those are usually selected and it kinda makes sense. Also not terribly difficult to do.

**Comment by brunocalado** [comment]
This could move to another place everything in the red box
![image](https://user-images.githubusercontent.com/4999783/133898347-672127cd-8a69-4238-86c3-b1fc6d344fdd.png)

**Comment by javierriveracastro** [comment]
I think that master global actions now take care of this.
