### ISSUE TITLE
Betterroll blocks dragging item from Actor to Item Directory 

### ISSUE THREAD

**Issue by JasonSK22** [javierriveracastro/betteroll-swade#328]
Unable to drag an item from an Actor to the Item Directory when Betterroll is active.  Able to produce this behavior in a swade world with just betterroll active.

**Comment by javierriveracastro** [comment]
This is related to the code that add the ability to drag items to other tokens or the macro bar.

When you start dragging an item we load it with our macro instead of the item data as foundry does.

When you drop the item in some place it will find the macro, and in most cases (like the item bar) Foundry doesn't know what to do with that data.

Solving this bug will probably require a complete rewrite of our drag and drop code to make it more intelligent. And this is probably a good thing but it will also take time.

The only fast workaround that I can think off is disabling our drag and drop, either totally or as some kind of option.

**Comment by JasonSK22** [comment]
Removing the drag and drop function will stop the ability to drop weapons and powers on tokens to target?  

Is there a way to have a toggle for the drag and drop function?  

Thank you for you work and time on this.

Jason

**Comment by javierriveracastro** [comment]
Yes, that and dragging to macro bar is what it does.

And yes I can add a toggle, but first I need to evaluate how much time a rewrite will take. At the end I'll need to rewrite it, so maybe making the toggle is just wasting time.

**Comment by javierriveracastro** [comment]
This should be solved in git with a revamp of drag and drop.
