### ISSUE TITLE
Rolling the attack on a card deselects selected combat options

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#338]
Is this a bug or expected behavior?
Previous versions would allow you to click on an attack option twice which would turn the option red and that option would be kept the next time that weapon was used.  Clicking once ( white) would only use that option for the current instance of the card and would go away the next time that weapon was used.

Currently clicking once would have the option removed after the attack roll while clicking twice (red) would keep the option up until the damage roll.  I don't know of a scenario where ,for instance, the wild attack modifier should only apply to the attack roll and not the damage roll.

If the current behavior is expected then, I will change my player's expectations.  Otherwise, I am just making you aware.

**Comment by javierriveracastro** [comment]
This is clearly a bug, no changing of behaviour was expected.

**Comment by javierriveracastro** [comment]
Now that I'm reading it slowly, this is usual behavior. The program have never remember nothing from another card in a new roll.

I mean, red means keep the modifier for all the rolls in this card. White means use it just for the next roll.

The behavior is the same for all modifiers, including the ones above the chat. This are the only ones that keep the mark between rolls.

So I feel that this bug is invalid, unless I'm reading it badly again.

**Comment by TheLaslo** [comment]
Thanks for confirming, that is what I needed to know.
