### ISSUE TITLE
Ignore Gang Up for global actions

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#354]
Some things like Block and Edges from other settings allow characters to ignore gang up. `target_has_edge` now allows to get edges owned by the tokens but as far as I can tell, there is currently no way to influence gang up. Introducing this would be beneficial for such egdes. A number provided to the setting would represent the points of ganging up that the target can ignore.

**Comment by grendel111111** [comment]
If it was a number could also be used to add to damage from pack tactics.

**Comment by javierriveracastro** [comment]
> f it was a number could also be used to add to damage from pack tactics.

I don't get this. Can you elaborate?

**Comment by grendel111111** [comment]
Sorry I was working on a couple of macros and it was late. For some reason I got confused and thought you could reference a number in BR2 like you do in macros. (So you could add "#total for gang up" into the additional damage of an action rather than "+1"). Clearly you can't and I was just getting mixed up.

**Comment by javierriveracastro** [comment]
The more I think about this, the more that I believe that this is an AE, not an action.

Not sure about the syntax, BTW.

**Comment by javierriveracastro** [comment]
I finally went for an active effect. The syntax is 'brsw-ac.gangup-reduction'. The idea is that all future AEs will start by brsw-ac.
