### ISSUE TITLE
Add roll to unshake to the "Character is Shaken" warning on cards

### ISSUE THREAD

**Issue by gravagehulk** [javierriveracastro/betteroll-swade#380]
This may be outside the scope of this module, but I go back and forth between Better Rolls and Swade Tools for one reason: The automation. Swade Tools automatically rolls to unshake for each combatant when their turn comes up. It's super handy for a GM (I always forget when someone is shaken, even if they have a status icon on them).

The other one is Vulnerable. After a Wild Attack, Better Rolls puts the Vulnerable status on the combatant, but it doesn't automatically roll off at the end of their next turn when they don't wild attack. Swade Tools does this.

I know that Swade tools is more about automation and Better Rolls is more about improving the combat flow. I was just wondering if doing either of these things are within scope of this module. It's really the only thing missing for me at this point.

**Comment by javierriveracastro** [comment]
Autorolling things is totally out of scope for better rolls.

That said, remembering states in a chat card at the end of the turn and adding an option to click to remove them, or somewhat remind player that they are shaken (and maybe make a card to unshake) are totally in scope.

Now the problem is how to did this UI and flow-wise.

For shaken, I'm thinking of doing it in two steps.

First: Add a warning to every card if the character is shaken or stunned.
Second: Create an unshake card and add a link/button to the above warning to show it.

I have no idea of how to manage vulnerable and than. The more that I think about it, the more that states should be Active Effects, but it will be a too big breakway from system.

**Comment by SalieriC** [comment]
Ideally, SWADE would support AE duration to terminate Vulnerable & Distracted automatically. I've created a relevant issue there a long time ago. Unfortunately it has not been addressed yet. For those two, BR2 should do nothing I think.
Regarding Shaken: We are still waiting for a core button on the sheet to roll to unshake. The System actually has a modifier built into the actors to modify the roll which is never used in any circumstance yet but FloRad repeatedly said that this will be a thing in the future so I would advice to wait (and possibly resort to macros in the meantime) until this is done to take control of that button once it's created. What would actually be helpful would be a confirmation of sorts. Like: Actor/Token is shaken -> BR2 roll is attempted; then, instead of making the roll (even if direct rolls are enabled), do not make the roll but show a warning in the chat card asking something along the line of "You are currently shaken, do you really want to make that roll?". This would probably be the least intrusive way of handling this.

On a side note: I am currently working on something to make rolls to unshake more streamlined. It won't be a part of BR2 but could enhance it in a way OP asked for while being compatible with BR2.

**Comment by javierriveracastro** [comment]
I'm trying to convince Flo to move states to active effects, but I'm probably failing.

I'm thinking more of adding a warning to the current chat card than making another card. Probably something in red at the top. The main reason is that this warning can be reusable for other states or even set with actions.

**Comment by grendel111111** [comment]
Is adding an actor_has_condition to BR2 an option or is that too complex? If you're using CUB then they can be referenced as they make an active effect for them. The current work around I am using detects if they have an active effect (from cub), puts a warning up to roll unshake. Then if they don't unshake it adds -1000 to their skill roll. If they do an action it will fail. But it means that you can let them take unshake roll without losing the roll they just make (You just delete the -1000 form the expanded result). It's not a good work around, but it might be useful to someone till a better option is done). 
![image](https://user-images.githubusercontent.com/80164119/148227840-e9f22d4b-9875-40a5-aa84-3057b7a2d8ce.png)

**Comment by gravagehulk** [comment]
The banner on the roll card would be helpful. I often (as GM) start making the attack before I even notice the status effect icon on the token because I use Token Hud for most of my attacks. It's a shame it can't be automated, but I totally understand. As it stands, better rolls is superior to Swade Tools in almost every way. I just miss the automation around shaken and vulnerable when I'm using it.

**Comment by javierriveracastro** [comment]
Just to be clear. It can be automated, it is just that I don't want to.

`Is adding an actor_has_condition to BR2 an option or is that too complex?`

Nope. But I feel it doesn't make a lot of sense, it would be the same work to add an option to check any value in the data path.

**Comment by javierriveracastro** [comment]
Is this too much?

![imaxe](https://user-images.githubusercontent.com/8113700/148256507-ee8fc027-c140-45b8-aad4-8f98a42058ec.png)

**Comment by javierriveracastro** [comment]
I moved it up.

![imaxe](https://user-images.githubusercontent.com/8113700/148256752-13c06c65-d9c0-4795-a2d1-05f4ef2e4689.png)

**Comment by javierriveracastro** [comment]
Now that I'm on it:

![imaxe](https://user-images.githubusercontent.com/8113700/148257328-0fa06ec4-853e-42ab-adb8-a9cd7ff88d26.png)

**Comment by SalieriC** [comment]
Don't think it's too much. Why the extra text though? Should read "This character is shaken." though I think. But that's nit-picky.

**Comment by javierriveracastro** [comment]
The extra text is for #358.

To summarize it can (will) be added using global actions.

**Comment by gravagehulk** [comment]
I like it!

**Comment by javierriveracastro** [comment]
I will left this issue open to add a unshaken card/roll (maybe I'll just rip the SWIM one and link it to the warning).

**Comment by SalieriC** [comment]
Feel free. I think it's rather complete and the results (certainly not the code 🤣 ) I consider well done. But add a hook so I can still inject my sweet SFX in SWIM. Also I demand to do the optional SWD version as well. :-P

**Comment by SalieriC** [comment]
I can probably provide the code. DM me on discord whenever you're ready to do this and I'll make some time to adjust and implement the code. =)

**Comment by javierriveracastro** [comment]
Basic rolling (with no support for edges, special abilities, etc...) is now in git.

Now I had to read SalieriC code and add all the possible modifiers.

**Comment by javierriveracastro** [comment]
After SalieriC help now most (or all) modifiers are supported. Let me see if I can hook this to the system alert window and close it.

**Comment by javierriveracastro** [comment]
Ummm.... should I simply show the card and remove the dialog, or would it be better to keep the dialog with an option to show the card.

It probably makes more sense to just show the card, the dialog looks like an unneeded step (you can always ignore the card).

**Comment by SalieriC** [comment]
Which dialogue? The one from the system? I'd say overwrite the dialogue with a custom one. BR2's philosophy was never to force automation. Make a dialogue that asks for the roll, to remove it without a roll and a cancel (optional since there is the `X` in the top right corner anyway). That would be my approach anyway.

**Comment by javierriveracastro** [comment]
It is not forcing nothing.

Option 1: Remove the system dialog, show the card. If you don't want it delete it.

Option 2: Change the system dialog (add a third button to show the card). Only show the card after clicking in the dialog.

I feel that 2 is more confusing and it just adds another step for little benefit. But I also feel than some people will find obtrusive just to show the card.

Maybe make another setting to autoshow the unshake card?

**Comment by SalieriC** [comment]
Honestly, I would find it more confusing if a card just appears without user action. I'd be very confused. And I know that I would be every time. That's not something I'd ever get used to. 🤣 
The dialogue could then just execute the roll directly instead of just showing the card, so no extra step and even more convenient because the dialogue appears in the middle of the screen where your eyes and mouse pointer are most likely to be. And it is bound to not be overlooked, unlike a chat card appearing w/o warning.

**Comment by Razortide** [comment]
My personal philosophy would be in favor of @javierriveracastro. If  I understood correctly, the question is if you want to reach the unshake roll with one click without the dialog or two clicks with the dialog. So, I haven't understood, what the perceived advantage of having one more step in between?

**Comment by javierriveracastro** [comment]
At the end I'll keep the dialog as it is. Messing with system like it is needed to remove it is going to give me extra work in the long run (it is likely going to break after system updates),
