### ISSUE TITLE
Targeting self or someone next to me with powers is using parry as TN

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#438]
So this looks like something related to the other defect I opened. Right now if I target myself or someone next to me and roll a power, it is using parry instead of 4. I'm just trying to cast boost trait or heal on myself an close ally and it should just be a 4 to succeed.

**Comment by SalieriC** [comment]
So the rules are:
> The attacker may only use a power or a one-handed ranged weapon (such as a firearm no larger than a pistol) when in melee. He may not fire rifles or other “long arms.” The TN is the defender’s Parry instead of Short Range as he struggles, wrestles back and forth, etc.

Now this leaves us with two questions:

1. It talks about attacker so does it really only apply to attacks? In which case BR2 could use token disposition to determine that?
2. The talk about Parry as TN mentions short range, so does it apply to powers at all (since they don't have range brackets)?

Personally I would've assumed the current way is fine because casting a power at a friend poses the same difficulties as shooting a pistol at a foe in this case: Foes can try to pull or push you away, grab your hand, whatever.

**Comment by javierriveracastro** [comment]
Why are you targeting someone to cast a heal o lower/boost trait?.

I mean, instead of trying to determine when a power is a kind of "shot" or not it will much easier to just let the human do it by targeting/no targeting. Unless you have a reason to target, like using another module, or something else.

**Comment by SalieriC** [comment]
> Why are you targeting someone to cast a heal o lower/boost trait?.
> 
> I mean, instead of trying to determine when a power is a kind of "shot" or not it will much easier to just let the human do it by targeting/no targeting. Unless you have a reason to target, like using another module, or something else.

Targeting the target of a spell is reasonable tbf. And if using modules like Automated-Animations it's also kinda necessary to show the effects on the proper target.

**Comment by basic-element** [comment]
> Why are you targeting someone to cast a heal o lower/boost trait?.
> 
> I mean, instead of trying to determine when a power is a kind of "shot" or not it will much easier to just let the human do it by targeting/no targeting. Unless you have a reason to target, like using another module, or something else.

I have custom macros that automate all these effects so if the caster targets 3 allies which can also include themself, the power will apply to all 3 targets.

**Comment by javierriveracastro** [comment]
I see.

So we have a problem, how do we determine when to use 4 and when to use parry. Disposition? Apply parry only when the spell has damage? Anyone has some official ruling about this?

**Comment by SalieriC** [comment]
I'll investigate. Please wait on resolving this, I'll reply when I have an answer.

**Comment by grendel111111** [comment]
I'm not sure if it is possible but could you always put both when in close combat?(TN 4 and Parry). The reason for this is that it will help determine if a power is not cast/ cast but misses/ or cast and hits.

**Comment by SalieriC** [comment]
There is no official answer to it yet: https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/59936-question-about-powers-in-melee

But hive mind (https://www.reddit.com/r/savageworlds/comments/ugldrm/question_about_powers_in_melee/) seems to agree on the following:

- On friendly targets, powers should always use a TN of 4, regardless of adjacent foes.
- Harmful ranged powers should count as ranged weapons in this specific case and thus apply Vulnerable if fired at non-adjacent targets whilst being adjacent to a foe.

**Comment by SalieriC** [comment]
We've got an official answer from Clint: https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/59936-question-about-powers-in-melee?p=60268#post60268
It doesn't make this issue any more easier to resolve I'm afraid. I think - considering that Bolt is the _only_ core power that is affected by Parry - it would probably be best to deactivate this feature for powers altogether. What do you think @javierriveracastro ?

**Comment by javierriveracastro** [comment]
That's probably makes sense. Or maybe use it when there is a damage roll. That way it will work for bolt as the rest of the spells that clint mentioned (like blast) are not targeted

**Comment by SalieriC** [comment]
I too have considered that but I think it wouldn't work as - with BR2 - you'll still end up targeting to properly apply damage. I think requiring people to first remove all their targets and then, after rolling the skill, target again is more demanding than applying the malus manually. We could try to add the malus on a localised name match but that will require us to cover settings individually and won't work if players rename their powers but that's probably the best solution if you want to keep it.

Otherwise we could take a look at making a tweaks like section that sets flags and enables configurability. That's likely the most future-proof solution. Maybe this is something we can take care of in SUCC and make it adaptable so that modules are able to add their own stuff to it. Not exactly condition stuff but it would be a great addition to the api of SUCC. But that's another topic best to be discussed elsewhere.

**Comment by javierriveracastro** [comment]
You're right. I will remove it for powers.

**Comment by javierriveracastro** [comment]
Done in git
