### ISSUE TITLE
Provide option to calculate range by grid

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#452]
Add a setting to allow change to how range for attacks is calculated.

Currently the calculation acts as if it were gridless.
In cases where grid is used for range this {"gridSpaces":true} should be added as the third parameter to canvas.grid.measureDistance.

**Comment by javierriveracastro** [comment]
Why? What would be the difference?

**Comment by TheLaslo** [comment]
scenario:
2 tokens, 18 squares distance diagonally between them.  ( 18 x18 )

using the in game ruler - distance = 18"
using the function without the option = 25.46"   ( pythagorean ) sqrt (
18^2 + 18^2)
using the function with the option = 18"

I had assumed that it was coded like this on purpose as some people play gridless, but using the grids requires us to manually remove the range penalties if there shouldn't be any.

**Comment by javierriveracastro** [comment]
It was coded this way on purpose because some people DOES use grids.

Sorry, but this doesn't make sense to me with the sw rules. There is a one well known system where diagonals cost less and circles are squares but it is not sw. 

You can configure the game rule so it measures distances correctly, BTW.

I will close this as Won't Fix. If you have other reasons of why I should implement it I'm open to listen to them, but for now it is a no.

**Comment by SalieriC** [comment]
Well, I'm that guy that plays using grids because grids are awesome and stuff. Makes the game a little easier I think. Anyway, I think the problem here is a UX one. Using grid there is currently no way for players to know the range applied by BR2 because the measure distance tool will show a different range. I don't really mind the small difference but I'm still with @TheLaslo on this. Ideally, BR2 should not use numbers which are unexpected by the user, if it can be helped. One solution to this might be reading `game.scenes.current.data.gridType` and setting the calculation method automatically if `gridType` is square or hex, matching the calculation in core.

**Comment by TheLaslo** [comment]
The current implementation exactly go against the rules you quoted.

Try and create two tokens, one w/ a ranged weapon of 5/10/20.
put the other token at 5 squares diagonally.  Use BR to attack w/ the
ranged weapon.
The attack will be at -2 because the target is beyond 5" but in fact
according to SW it should only be 5 inches of range.

Please check that out before closing.

**Comment by javierriveracastro** [comment]
Can you quote where the SW rules says that a token 5 squares diagonally from another is just 5" away?

BTW @SalieriC , he is not asking for rounding, unless I understand it wrong, he is asking that two tokens that are five squares horizontal and five square vertically one from other, should be treated like they are 5 squares away.

**Comment by javierriveracastro** [comment]
BTW, if someone wants to implement this, as long as it is optional and not default, I'll happily merge it.

But I'm not spend time to implement this. It is probably my fault but it would totally breaks my immersion in a game. Non euclidean combats are a no-no to me, but I understand that some people could prefer the easiness of counting diagonals to any kind of similarity to the real world.

**Comment by SalieriC** [comment]
To be fair @TheLaslo, Savage Worlds is not really meant to be played using grid. Savage Worlds is meant to be played gridless and thus meant to be calculated rather precise. I agree it should calculate the stuff differently if using grid but what you just wrote is _not_ contrary to the rules.

@javierriveracastro no I think the problem here is diagonal distance:
![image](https://user-images.githubusercontent.com/1230041/170828209-a30d941d-4719-495f-8267-bde45842f4a4.png)

**Comment by TheLaslo** [comment]
No sorry, I can't.  I thought you misunderstood what I was asking for and
stating that in your response ( I totally missed "but it is not sw" ).

My preference comes from in person gaming where we wouldn't have wanted to
pull out a tape measure or ruler every time we fired a shot when we already
had a battlemat grid available.

I'll see what I can do to make a modification to the settings to allow
this, but I might need help with creating a PR on github.  I'm an old C#
sourcesafe guy who still needs to internalize the git methodology.

**Comment by SalieriC** [comment]
Was about to look into the code @TheLaslo but I hate this kind of math, so feel free. :D
Let me know when you've got something ready and we can work that out. Discord handle: SalieriC#8263
Start by creating a fork: 
![image](https://user-images.githubusercontent.com/1230041/170829389-3e293e1d-6a22-493c-86eb-9c89b39db05d.png)
Then look at https://github.com/javierriveracastro/betteroll-swade/blob/7d5b66bbdc21a2b1e34d2aa16f847b6648465ea6/betterrolls-swade2/scripts/skill_card.js#L221-L253
on your fork. Once you've got the code ready let me know. Creating a PR is a breeze from there.

**Comment by TheLaslo** [comment]
PR has been created

**Comment by javierriveracastro** [comment]
PR merged
