### ISSUE TITLE
Some traits have full description, some just page pointer in v10

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#499]
**Some traits have full description, some just page pointer in v10**

Foundry: 10.287
Savage Worlds Adventure Edition: 2.0.5
Savage Worlds Adventure Edition: 2.0.0
BR2: 3.2
SUCC: 0.2.0
SWIM: 0.18.5

Some traits, e.g., Athletics, only have a pointer to the page in the SWADE manual in their Description ...
![image](https://user-images.githubusercontent.com/64320/194932148-a65e046a-a700-42b7-b8bf-32699a3fdab5.png)

Whereas others, e.g., Fighting, are getting the full details ...
![image](https://user-images.githubusercontent.com/64320/194932327-a24b801b-be87-4d77-91a7-2c33883df28b.png)

_... I've checked in my "SWADE Skills" compendium, and the Athletics skill does have the full details._

**Comment by javierriveracastro** [comment]
This is because some traits are from the SWADE compendium and the other is from the premium module. 

This likely happened because Athletics by default is autoadded from the system compendiums at character creation, while you have probably added Fighting by drag and dropping from the premium module.

You can change that in the system settings:

![imaxe](https://user-images.githubusercontent.com/8113700/195019977-54f94735-1cb0-4d4f-968a-c6185dba59ee.png)

But anyway there is nothing related to BR2 in that so I close the issue. If you have any questions or issues you can reopen it.

**Comment by javierriveracastro** [comment]
If you want to fix that character there is a macro in the premium module that will find and substitute all basic skills for the full ones, but I can't remember its name. Or you can just delete Athletics from the PC and drag and drop the full one.

**Comment by steveculshaw** [comment]
@javierriveracastro Many thanks for explaining Javier. Apologies for posting it against BR2.
