### ISSUE TITLE
Request: Switch the default values for All Thumbs, Can't Swim, and (maybe) Hard of Hearing to off?

### ISSUE THREAD

**Issue by ddbrown30** [javierriveracastro/betteroll-swade#573]
These indrances default to "on" even though they are rarely used. Can we please get them switched?

All Thumbs and Can't Swim almost never come into play and should definitely be off.
Hard of Hearing affects a roll less often than it doesn't and would probably be better defaulted to off.

**Comment by javierriveracastro** [comment]
Duplicate: #433

**Comment by ddbrown30** [comment]
Bringing over my reasoning from Discord. (I'll just drop the Hard of Hearing request and focus on the others.)

For All Thumbs, it currently applies to every trait type. This means that common knowledge, notice, persuasion, etc. are all being affected by All Thumbs by default. Even in a sci-fi setting it's hard to argue that this should be the default behaviour. Putting aside that issue for a moment, I would also argue that even in a modern or futuristic setting, a player that chose this hindrance will have built their character around it. The majority of actions that character is going to attempt will not be affected by All Thumbs.

For Can't Swim, I think this one should be pretty self-evident. The vast, vast majority of athletics checks a player is going to attempt will not be swimming regardless of setting.

**Comment by brunocalado** [comment]
Always off is better. The game is to dynamic to predict an behavior. But, my experience shows always off is better.

A fancy solution is make this button remember the last option.

**Comment by steveculshaw** [comment]
I'm not sure how "All Thumbs" detects the "All Thumbs inflicts a −2 penalty when using mechanical or electrical devices"

We've got two players who independently have taken the "Can't Swim", and the default of "On" is a constant pain. They're rolling Athletics at various times; climbing, jumping, etc. and have never (so far) had to do any swimming. 
This is in a fantasy game. 

Not got "Hard of Hearing" in the game, but again having to remember to remove it when it's just a "Notice" check, rather than enable it when it's just an "audio Notice" check feels the wrong way round.

So my experience is off by default is the better option

**Comment by grendel111111** [comment]
Yes. Let's remove default on. However I would suggest we remove them from hindrances and edges groups. I think giving them their own group will work as a visual reminder. I use swim and climb in athletics and put any a/h that affect swimming or climbing in those groups. Notice could have a "Hearing Check" so it reminds you that if it is hearing when you roll notice you should open that panel.

**Comment by javierriveracastro** [comment]
Done
