### ISSUE TITLE
BR2 not respecting Name mystification from Anonymous.

### ISSUE THREAD

**Issue by Deadlander** [javierriveracastro/betteroll-swade#615]
When both Anonymous mod and BR2 are active, and the name of the creature has been changed by Anonymous, BR2 is still showing the original actor's name.
For example: If the players come across a tentamort (Pathfinder for Savage Worlds), with Anonymous on, it is showing in chat as "A Strange Creature" with BR2 turned off. But, if BR2 is turned on, it ignores the temporary name change, and lists it as tentamort.

**Comment by javierriveracastro** [comment]
I'm not sure why it is not working, but I bet it is because we are both using the same hook to change the render message and betterrolls goes afterwards.

I'm not sure if I can do something to change it except for firing a Hook in BR2 and having Anonymous hook to it. But this will need the collaboration of its developer. 

Anyway, adding the Hook can be useful for other modules that use BR2 so I'm going to probably do it anyway (I'll think about it a little longer first)

**Comment by javierriveracastro** [comment]
Hook added (BRSW-CardRendered).
