### ISSUE TITLE
Apply the proper trait penalty when the 'default ROF' user setting is higher than 1

### ISSUE THREAD

**Issue by JosephA1997** [javierriveracastro/betteroll-swade#742]
Right now when the user setting for 'default rate of fire' is set to the weapon's ROF and it's higher than 1, it won't automatically apply the appropriate ROF penalty and needs to be selected manually.

**Comment by javierriveracastro** [comment]
The problem here is that there is no "proper trait penalty" for multiple ROF. You are probably thinking about recoil, but this only applies to firearms. ROF is used by spells, frenzy, future weapons, bows with some edges, etc...

Luckily the actions for ROF already include that penalty if you own the core rules, but there is no way to know if it should apply to base system weapons.

The only idea that i have here is to default to ROF 1, that should work well for Core Rules owners, as their weapons will have ROF actions already set. The settings option to use full ROF will be keep, hoping that people who knows about it can use recoil.

Or maybe try to add some way to detect if recoil should be used only with basic data, but this looks challenging.

**Comment by JosephA1997** [comment]
I think making the setting default to ROF 1 will be just fine.

**Comment by javierriveracastro** [comment]
Changed.
