### ISSUE TITLE
Shooting defaults to full auto

### ISSUE THREAD

**Issue by Raileth** [javierriveracastro/betteroll-swade#94]
Shooting defaults to Full Auto when a weapon has a RoF higher than 1. This is contrary to how the default  rolls work where shooting is set to a single shot and if autofire is needed then additional actions and effects are setup.

The workaround is to create a separate action for a single shot, however if better rolls is then not used there is no option for a full auto shot. It would make more sense to default to a single shot and then where full auto is required a separate action can be created. 
Alternatively where a weapon has a RoF greater than 1 the interface could ask how many shots are being fired.

**Comment by javierriveracastro** [comment]
That's how it should work.
You can set the ROF on the "chat window" just above the chat.

And this is the only way to support people who don't use actions. I want to support the ability to have different weapons for different actions of the same real "weapon" (a normal sword and a frenzy sword) so that you can roll them with a single click.

So, unless I'm missing something this is Wont'Fix. Sorry.

**Comment by Raileth** [comment]
it might be me but I cant see where to set the RoF on the chat window - can you point me in the right direction?

Thanks

**Comment by javierriveracastro** [comment]
![chat_modifiers](https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/chat_modifiers.png)

In the above image, "number of trait dice", ROF is that just.

**Comment by Raileth** [comment]
thanks
